const PAL_CATEGO = {
// -- A -- //
  "Accent": ["qualitative", "stepped"],
  "Acton": ["colorblind", "sequential"],
  "AfmHot": ["sequential"],
  "AgGrnYl": ["qualitative", "sequential"],
  "AgSunset": ["qualitative", "sequential"],
  "Algae": ["sequential"],
  "Alphabet": ["qualitative"],
  "Amber": ["sequential"],
  "Amethyst": ["sequential"],
  "Amp": ["sequential"],
  "Antique": ["qualitative", "stepped"],
  "Apple": ["colorblind", "sequential"],
  "Aquatic1": ["qualitative", "stepped"],
  "Aquatic2": ["qualitative", "stepped"],
  "Aquatic3": ["qualitative", "stepped"],
  "Arctic": ["sequential"],
  "ArmyRose": ["divergent", "sequential"],
  "Autumn": ["dark", "qualitative", "sequential"],
// -- B -- //
  "Balance": ["cyclic", "divergent", "sequential"],
  "Bam": ["colorblind", "divergent", "sequential"],
  "Bamako": ["colorblind", "sequential"],
  "BamO": ["colorblind", "cyclic", "divergent", "sequential"],
  "Batlow": ["colorblind", "divergent", "sequential"],
  "BatlowK": ["colorblind", "divergent", "sequential"],
  "BatlowW": ["colorblind", "divergent", "sequential"],
  "Berlin": ["colorblind", "divergent", "sequential"],
  "Bilbao": ["colorblind", "sequential"],
  "Binary": ["qualitative", "sequential"],
  "Blackbody": ["divergent", "qualitative", "sequential"],
  "BlindFish": ["divergent", "qualitative", "sequential"],
  "BlueDarkOrange12": ["divergent", "sequential"],
  "BlueDarkOrange18": ["divergent", "sequential"],
  "BlueDarkRed12": ["divergent", "sequential"],
  "BlueDarkRed18": ["divergent", "sequential"],
  "BlueGray": ["divergent", "sequential"],
  "BlueGreen": ["divergent", "sequential"],
  "BlueGrey": ["divergent", "sequential"],
  "BlueOrange8": ["divergent", "sequential"],
  "BlueOrange10": ["divergent", "sequential"],
  "BlueOrange12": ["stepped"],
  "BlueOrangeRed": ["divergent", "sequential"],
  "BlueRed": ["qualitative", "stepped"],
  "BlueRedPLY": ["qualitative", "sequential"],
  "Blues": ["sequential"],
  "Blues7": ["sequential"],
  "Blues10": ["sequential"],
  "BluesCP": ["sequential"],
  "BluGrn": ["sequential"],
  "BluYl": ["sequential"],
  "Bold": ["qualitative"],
  "Bone": ["sequential"],
  "BrBG": ["divergent", "sequential"],
  "BRG": ["qualitative", "sequential"],
  "Broc": ["colorblind", "divergent", "sequential"],
  "BrocO": ["colorblind", "cyclic", "divergent", "sequential"],
  "BrownBlue10": ["divergent", "sequential"],
  "BrownBlue12": ["divergent", "sequential"],
  "BrwnYl": ["sequential"],
  "Bubblegum": ["sequential"],
  "Buda": ["colorblind", "sequential"],
  "BuGn": ["sequential"],
  "Bukavu": ["colorblind", "stepped"],
  "BuPu": ["sequential"],
  "Burg": ["sequential"],
  "BurgYl": ["sequential"],
  "BurningGrass": ["divergent", "qualitative", "sequential"],
  "BWR": ["dark", "divergent", "qualitative", "sequential"],
// -- C -- //
  "Cavalcanti": ["qualitative", "stepped"],
  "Chevalier": ["qualitative", "stepped"],
  "Chroma": ["colorblind", "stepped"],
  "Cividis": ["sequential"],
  "Classic": ["stepped"],
  "CMRmap": ["qualitative", "sequential"],
  "ColorBlind": ["qualitative"],
  "Cool": ["dark", "qualitative", "sequential"],
  "CoolCP": ["sequential"],
  "CoolWarm": ["divergent", "sequential"],
  "Copper": ["sequential"],
  "CopperCM": ["colorblind", "cyclic", "divergent", "sequential"],
  "Cork": ["colorblind", "divergent", "sequential"],
  "CorkO": ["colorblind", "cyclic", "divergent", "sequential"],
  "Cosmic": ["sequential"],
  "Cube1": ["stepped"],
  "Cubehelix1": ["stepped"],
  "Cubehelix2": ["stepped"],
  "Cubehelix3": ["stepped"],
  "CubeYF": ["sequential"],
  "Curl": ["divergent", "sequential"],
// -- D -- //
  "Darjeeling1": ["qualitative"],
  "Darjeeling2": ["qualitative", "stepped"],
  "Darjeeling3": ["qualitative", "stepped"],
  "Darjeeling4": ["qualitative", "stepped"],
  "Dark2": ["qualitative", "stepped"],
  "Dark24": ["qualitative", "stepped"],
  "DarkMint": ["sequential"],
  "Davos": ["colorblind", "sequential"],
  "Deep": ["sequential"],
  "Delta": ["cyclic", "divergent", "sequential"],
  "Dense": ["sequential"],
  "Devon": ["colorblind", "sequential"],
  "Dusk": ["stepped"],
// -- E -- //
  "Earth": ["divergent", "sequential"],
  "EarthCP": ["sequential"],
  "Eclipse": ["stepped"],
  "Electric": ["divergent", "sequential"],
  "Ember": ["sequential"],
  "Emerald": ["sequential"],
  "Emergency": ["colorblind", "cyclic", "divergent", "sequential"],
  "Emrld": ["sequential"],
// -- F -- //
  "Fall": ["divergent", "sequential"],
  "FallCM": ["sequential"],
  "FantasticFox1": ["divergent", "qualitative", "sequential"],
  "FantasticFox2": ["qualitative", "stepped"],
  "Fes": ["colorblind", "stepped"],
  "Fire": ["sequential"],
  "Flag": ["stepped"],
  "Flamingo": ["sequential"],
  "Freeze": ["sequential"],
  "Fusion": ["cyclic", "divergent", "sequential"],
// -- G -- //
  "G10": ["cyclic", "qualitative"],
  "GasFlame": ["qualitative", "sequential"],
  "Gem": ["sequential"],
  "GeoRainbow": ["qualitative", "stepped"],
  "Geyser": ["divergent", "sequential"],
  "GhostLight": ["stepped"],
  "GistEarth": ["stepped"],
  "GistGray": ["sequential"],
  "GistHeat": ["sequential"],
  "GistNcar": ["stepped"],
  "GistRainbow": ["dark", "stepped"],
  "GistStern": ["stepped"],
  "Glasgow": ["colorblind", "sequential"],
  "GnBu": ["sequential"],
  "Gnuplot": ["sequential"],
  "Gnuplot2": ["sequential"],
  "Gothic": ["sequential"],
  "GrandBudapest1": ["divergent", "qualitative", "sequential"],
  "GrandBudapest2": ["divergent", "qualitative", "sequential"],
  "GrandBudapest3": ["qualitative", "stepped"],
  "GrandBudapest4": ["qualitative", "stepped"],
  "GrandBudapest5": ["qualitative", "stepped"],
  "Gray": ["sequential"],
  "GrayC": ["colorblind"],
  "GreenGrey": ["divergent", "sequential"],
  "GreenMagenta": ["divergent", "sequential"],
  "GreenOrange": ["qualitative"],
  "Greens": ["sequential"],
  "GreensCP": ["sequential"],
  "Greys": ["sequential"],
  "GreysCP": ["sequential"],
  "Guppy": ["divergent", "sequential"],
// -- H -- //
  "Haline": ["sequential"],
  "Hawaii": ["colorblind", "stepped"],
  "Heart": ["sequential"],
  "Holly": ["colorblind", "divergent", "sequential"],
  "Horizon": ["sequential"],
  "Hot": ["sequential"],
  "HotPLY": ["qualitative", "sequential"],
  "HSV": ["cyclic", "stepped"],
// -- I -- //
  "Ice": ["sequential"],
  "IceBurn": ["divergent", "sequential"],
  "Imola": ["colorblind", "sequential"],
  "Inferno": ["sequential"],
  "Infinity": ["cyclic", "stepped"],
  "IsleOfDogs1": ["qualitative", "stepped"],
  "IsleOfDogs2": ["qualitative", "stepped"],
  "IsleOfDogs3": ["qualitative", "stepped"],
// -- J -- //
  "Jet": ["dark", "stepped"],
  "JetPLY": ["stepped"],
  "JimSpecial": ["sequential"],
  "Jungle": ["sequential"],
// -- L -- //
  "Lajolla": ["colorblind", "sequential"],
  "Lapaz": ["colorblind", "stepped"],
  "Lavender": ["sequential"],
  "Lemon": ["dark", "qualitative", "sequential"],
  "Light24": ["qualitative"],
  "Lilac": ["stepped"],
  "LinearL": ["stepped"],
  "Lipari": ["colorblind", "sequential"],
  "Lisbon": ["colorblind", "divergent", "sequential"],
// -- M -- //
  "Magenta": ["sequential"],
  "Magma": ["sequential"],
  "Managua": ["colorblind", "divergent", "sequential"],
  "Margot1": ["qualitative", "stepped"],
  "Margot2": ["qualitative", "stepped"],
  "Margot3": ["qualitative", "stepped"],
  "Matter": ["sequential"],
  "Mendl": ["qualitative", "stepped"],
  "MidGray": ["qualitative", "stepped"],
  "Mint": ["sequential"],
  "Moonrise1": ["qualitative", "stepped"],
  "Moonrise2": ["qualitative", "stepped"],
  "Moonrise3": ["qualitative", "stepped"],
  "Moonrise4": ["qualitative", "stepped"],
  "Moonrise5": ["qualitative", "stepped"],
  "Moonrise6": ["qualitative", "stepped"],
  "Moonrise7": ["qualitative", "stepped"],
// -- N -- //
  "Navia": ["colorblind", "sequential"],
  "NaviaW": ["colorblind", "sequential"],
  "Neon": ["stepped"],
  "NipySpectral": ["qualitative", "stepped"],
  "Nuclear": ["sequential"],
  "Nuuk": ["colorblind", "stepped"],
// -- O -- //
  "Ocean": ["stepped"],
  "OceanCM": ["sequential"],
  "OkabeIto": ["colorblind", "qualitative", "stepped"],
  "Oleron": ["colorblind", "stepped"],
  "OrangeBlue": ["divergent", "sequential"],
  "OrangeGrey": ["divergent", "sequential"],
  "Oranges": ["sequential"],
  "OrangesCP": ["sequential"],
  "OrRd": ["sequential"],
  "OrYel": ["sequential"],
  "Oslo": ["colorblind", "sequential"],
  "Oxy": ["stepped"],
// -- P -- //
  "Paired": ["qualitative", "stepped"],
  "Pastel": ["qualitative", "stepped"],
  "Pastel1": ["qualitative", "stepped"],
  "Pastel2": ["qualitative", "stepped"],
  "PastelRainbow": ["qualitative", "stepped"],
  "Peach": ["sequential"],
  "Pepper": ["sequential"],
  "PerceptualRainbow": ["sequential"],
  "Petroff6": ["colorblind", "qualitative", "stepped"],
  "Petroff8": ["colorblind", "qualitative", "stepped"],
  "Petroff10": ["colorblind", "qualitative", "stepped"],
  "Phase": ["cyclic", "stepped"],
  "Picnic": ["divergent", "sequential"],
  "Pink": ["sequential"],
  "PinkGreen": ["divergent", "sequential"],
  "PinkGrey": ["divergent", "sequential"],
  "Pinks": ["sequential"],
  "PinkYl": ["sequential"],
  "PiYG": ["divergent", "sequential"],
  "Plasma": ["sequential"],
  "Plotly": ["qualitative"],
  "Portland": ["divergent", "sequential"],
  "PrGn": ["divergent", "sequential"],
  "Pride": ["colorblind", "cyclic", "divergent", "sequential"],
  "Prinsenvlag": ["divergent", "sequential"],
  "Prism": ["dark", "stepped"],
  "PrismCC": ["qualitative", "stepped"],
  "PuBu": ["sequential"],
  "PuBuGn": ["sequential"],
  "PuOr": ["divergent", "sequential"],
  "PuRd": ["sequential"],
  "Purp": ["sequential"],
  "Purple": ["sequential"],
  "PurpleGray": ["qualitative", "stepped"],
  "PurpleGrey": ["divergent", "sequential"],
  "Purples": ["sequential"],
  "PurplesCP": ["sequential"],
  "PurpOr": ["sequential"],
// -- R -- //
  "Rainbow": ["dark", "stepped"],
  "RainbowCP": ["stepped"],
  "RainbowPLY": ["qualitative", "stepped"],
  "Rainforest": ["colorblind", "stepped"],
  "RdBu": ["divergent", "sequential"],
  "RdGy": ["divergent", "sequential"],
  "RdPu": ["sequential"],
  "RdYlBu": ["divergent", "sequential"],
  "RdYlGn": ["divergent", "sequential"],
  "Red": ["sequential"],
  "RedGrey": ["divergent", "sequential"],
  "RedOr": ["sequential"],
  "Reds": ["sequential"],
  "RedsCP": ["sequential"],
  "RedShift": ["divergent", "sequential"],
  "RedTeal": ["divergent", "sequential"],
  "RedYellowBlue": ["divergent", "sequential"],
  "Roma": ["colorblind", "divergent", "sequential"],
  "RomaO": ["colorblind", "cyclic", "stepped"],
  "Royal1": ["divergent", "qualitative", "sequential"],
  "Royal2": ["qualitative", "stepped"],
  "Royal3": ["qualitative", "stepped"],
// -- S -- //
  "Safe": ["colorblind", "qualitative", "stepped"],
  "Sapphire": ["sequential"],
  "Seasons": ["colorblind", "cyclic", "divergent", "sequential"],
  "Seaweed": ["divergent", "sequential"],
  "Seismic": ["dark", "divergent", "qualitative", "sequential"],
  "Sepia": ["sequential"],
  "Set1": ["qualitative", "stepped"],
  "Set2": ["qualitative", "stepped"],
  "Set3": ["qualitative", "stepped"],
  "ShiftRainbow": ["qualitative", "stepped"],
  "SineBow": ["stepped"],
  "Solar": ["sequential"],
  "Spectral": ["divergent", "sequential"],
  "Speed": ["sequential"],
  "Spring": ["dark", "qualitative", "sequential"],
  "Summer": ["dark", "qualitative", "sequential"],
  "SunBurst": ["sequential"],
  "Sunset": ["sequential"],
  "SunsetDark": ["sequential"],
  "Swamp": ["sequential"],
// -- T -- //
  "T10": ["qualitative", "stepped"],
  "Tab10": ["qualitative"],
  "Tab20": ["dark", "qualitative", "stepped"],
  "Tab20b": ["dark", "qualitative", "semantic", "stepped"],
  "Tab20c": ["dark", "qualitative", "semantic", "stepped"],
  "TableauLight": ["qualitative", "stepped"],
  "TableauMedium": ["qualitative", "stepped"],
  "TdocBW": ["semantic"],
  "TdocCol": ["qualitative", "semantic"],
  "TdocDark": ["dark", "qualitative", "semantic"],
  "Teal": ["sequential"],
  "TealGrey": ["divergent", "sequential"],
  "TealGrn": ["sequential"],
  "TealRose": ["divergent", "sequential"],
  "Teals": ["sequential"],
  "Tempo": ["sequential"],
  "Temps": ["divergent", "sequential"],
  "Terrain": ["dark", "stepped"],
  "Thermal": ["sequential"],
  "Tofino": ["colorblind", "divergent", "sequential"],
  "Tokyo": ["colorblind", "sequential"],
  "Torch": ["sequential"],
  "Toxic": ["sequential"],
  "TrafficLight": ["qualitative", "stepped"],
  "Tree": ["sequential"],
  "Tropic": ["divergent", "sequential"],
  "Tropical": ["sequential"],
  "Turbid": ["sequential"],
  "Turbo": ["stepped"],
  "Turku": ["colorblind", "sequential"],
  "Twilight": ["cyclic", "divergent", "sequential"],
// -- V -- //
  "Vanimo": ["colorblind", "divergent", "sequential"],
  "Vik": ["colorblind", "divergent", "sequential"],
  "VikO": ["colorblind", "cyclic", "divergent", "sequential"],
  "Viola": ["cyclic", "divergent", "sequential"],
  "Viridis": ["dark", "sequential"],
  "Vivid": ["qualitative", "stepped"],
  "Voltage": ["sequential"],
// -- W -- //
  "Warm": ["sequential"],
  "Water": ["sequential"],
  "Waterlily": ["cyclic", "divergent", "sequential"],
  "Watermelon": ["colorblind", "divergent", "sequential"],
  "Wildfire": ["colorblind", "divergent", "sequential"],
  "Wind": ["sequential"],
  "Winter": ["dark", "qualitative", "sequential"],
  "Wistia": ["colorblind", "sequential"],
// -- Y -- //
  "YellowGrey": ["divergent", "sequential"],
  "YellowPurple": ["divergent", "sequential"],
  "Yellows": ["sequential"],
  "YlGn": ["sequential"],
  "YlGnBu": ["sequential"],
  "YlOrBr": ["dark", "sequential"],
  "YlOrRd": ["dark", "sequential"],
  "YlOrRdCBW": ["sequential"],
// -- Z -- //
  "Zissou": ["qualitative", "stepped"]
};