// Fictive list just for tests...
const palettesData = {
  "Accent": 10,
  "Alizari": 12,
  "Amber": 9,
  "Azure": 8,
  "Bordeaux": 11,
  "Bronze": 10,
  "Berry": 14,
  "Cyan": 10,
  "Cobalt": 12,
  "Crimson": 8,
  "Default": 5,
  "DeepSea": 15,
  "Dragon": 10,
  "Emerald": 10,
  "Electric": 7,
  "Earthy": 12,
  "Fuchsia": 10,
  "Forest": 11,
  "Fire": 9,
  "Gold": 8,
  "Graphite": 10,
  "Grape": 13,
  "Hot": 10,
  "Heliotrope": 10,
  "Indigo": 10,
  "XyZ": 6
};
