# ------------------------- #
# -- RGB FLOAT PRECISION -- #
# ------------------------- #

# Optimizing data weight: 4-decimal precision exceeds human
# visual acuity and ensures 8-bit color integrity.
PRECISION: 6


# ---------------------------- #
# -- SEMANTIC CONTENT TYPES -- #
# ---------------------------- #

# We associate each category with allowed alias.

CATEGORY:
#  + C
  colorblind:
    title: Colorblind palettes
    desc: >
      Colorblind palettes provide high-contrast hues specifically
      optimized for users with color vision deficiency.
    alias:   # No alias.

  cyclic:
    title: Cyclic palettes
    desc: >
      Cyclic palettes create seamless loops for periodic data, such
      as angles, seasons, or 24-hour cycles.
    alias:
      - circular
      - cyclical

#  + D
  dark:
    title: Dark palettes
    desc: >
      Dark palettes offer high-contrast schemes specifically
      optimized for terminal interfaces and dark-mode backgrounds.
    alias:   # No alias.

  divergent:
    title: Divergent palettes
    desc: >
      Divergent palettes highlight deviations from one or more
      midpoints toward contrasting extremes.
    alias:
      - div
      - diverging

#  + Q
  qualitative:
    title: Qualitative palettes
    desc: >
      Qualitative palettes use distinct hues to separate categorical
      data without implying any order or hierarchy.
    alias:
      - qual
      - discrete
      - aggregation

#  + S
  semantic:
    title: Semantic palettes
    desc: >
      Semantic palettes assign colors to categories — such as UI
      states, system status, or pedagogical elements — to convey
      immediate meaning.
    alias:
      - sem

  sequential:
    title: Sequential palettes
    desc: >
      Sequential palettes represent ordered data using a single or
      multi-hue gradient with increasing lightness.
    alias:
      - seq
      - scientific colormaps
      - quantitative
      - sequentialMultiHue
      - sequentialSingleHue
