# Optimizing data weight: 4-decimal precision exceeds human visual
# acuity and ensures 8-bit color integrity.
PRECISION: 4

# The choice of `30` makes it possible to consider, for example,
# semantic colors associated with two colors (for example, hovered
# link, visited link, inactive link).s
AUTO_QUAL_CATEGO_SIZE: 30

# We associate each category with allowed alias.
CATEGORY:
# OK????   Palettes specifically designed to be accessible to people with color vision deficiency (CVD), ensuring high contrast and legibility.
  colorblind: # No alias.

# OK????   Used for data with a natural midpoint (e.g., zero, average, or neutral). Colors diverge from the center towards two different extremes.
  divergent:
    - div
    - diverging

# OK????   Best for categorical or nominal data where no order is implied (e.g., different labels, groups, or names).
  qualitative:
    - qual
    - discrete

# OK????   Ideal for data that follows a logical order from low to high value. Usually based on a single hue or multiple hues with increasing lightness.
  sequential:
    - seq

# OK????   For data that repeats periodically (e.g., 24h time, angles, or seasons). The start and end colors are identical to create a seamless loop.
  cyclic: # No alias.

# OK????   High-contrast palettes optimized for terminal interfaces or applications using dark backgrounds.
  dark: # No alias.
