# ------------------------- #
# -- RGB FLOAT PRECISION -- #
# ------------------------- #

# Optimizing data weight: 4-decimal precision exceeds human
# visual acuity and ensures 8-bit color integrity.
PRECISION: 4


# ---------------------------- #
# -- SEMANTIC CONTENT TYPES -- #
# ---------------------------- #

# We associate each category with allowed alias.

CATEGORY:
#  + A
  aggregation:
    desc: |
      Aggregation palettes optimize contrast for high-density data,
      such as heatmaps, using progressive luminance ramps.
    alias:   # No alias.

#  + C
  colorblind:
    desc: |
      Colorblind palettes provide high-contrast hues specifically
      optimized for users with color vision deficiency.
    alias:   # No alias.

  cyclic:
    desc: |
      Cyclic palettes create seamless loops for periodic data, such
      as angles, seasons, or 24-hour cycles.
    alias:
      - circular

#  + D
  dark:
    desc: |
      Dark palettes offer high-contrast schemes specifically
      optimized for terminal interfaces and dark-mode backgrounds.
    alias:   # No alias.

  divergent:
    desc: |
      Divergent palettes highlight deviations from one or more
      midpoints toward contrasting extremes.
    alias:
      - div
      - diverging

#  + Q
  qualitative:
    desc: |
      Qualitative palettes use distinct hues to separate categorical
      data without implying any order or hierarchy.
    alias:
      - qual
      - discrete

#  + S
  semantic:
    desc: |
      Semantic palettes assign colors to categories — such as UI
      states, system status, or pedagogical elements — to convey
      immediate meaning.
    alias:
      - sem

  sequential:
    desc: |
      Sequential palettes represent ordered data using a single or
      multi-hue gradient with increasing lightness.
    alias:
      - seq
      - scientific colormaps
      - quantitative
