# ----------------------------- #
# -- PALETTE SOURCE PRIORITY -- #
# ----------------------------- #

# Priority coefficients: higher values = higher priority.
#
# Projects with equal priority values are non-comparable.


# -- STANDALONE SOURCES -- #
#
# HIGH PRIORITY

#  + C
CARBONPLAN : 10
CARTOCOLORS: 10
CMASHER    : 10
CMOCEAN    : 10
COLORBREWER: 10
COLORMAPS  : 10
CUBEHELIX  : 10

#  + L
LIGHTBARTLEIN: 10

#  + M
MYCARTA: 10

#  + N
NCLCOLTABLES: 10

#  + P
PLOTLY: 10

#  + S
SCIENTIFIC-COLOUR-MAPS: 10

#  + T
TABLEAU: 10

#  + W
WESANDERSON: 10


# -- COMPLEMENTARY EXTERNAL SOURCES -- #
#
# LOW PRIORITY

#  + A
"@PRISM" : -30
ASYMPTOTE: -20

#  + M
MATPLOTLIB: -10
